CREATE TABLE [dbo].[Patient] (
    [ID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[ID_Number] [nvarchar](50) NOT NULL,
	[Gender] [char](1) NOT NULL,
	[DOB] [nvarchar](50) NOT NULL,
	[Cell_Number] [nvarchar](50) NOT NULL,
	[Street_Address] [nvarchar](50) NOT NULL,
	[Suburb] [nvarchar](50) NOT NULL,
	[City] [nvarchar](50) NOT NULL,
	[Country] [nvarchar](50) NOT NULL,
	[Medical_Aid_ID] [int] NOT NULL,
	[Doctor_ID] [int] NOT NULL,
	[User_ID] [int] NOT NULL,
	[Allergies] [nvarchar](500) NULL,
	[PreviousIllnesses] [nvarchar](500) NULL,
	[PreviousMedication] [nvarchar](500) NULL,
	[RiskFactors] [nvarchar](500) NULL,
	[SocialHistory] [nvarchar](500) NULL,
	[FamilyHistory] [nvarchar](500) NULL,
	[Email] [nvarchar](50) NULL,
	[DeletedStatus] [int] NULL DEFAULT ((0)),
	[RegistrationDate] [nvarchar](50) NULL DEFAULT '2016-10-20'
    CONSTRAINT [PK_Patient] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_Patient_Doctors] FOREIGN KEY ([Doctor_ID]) REFERENCES [dbo].[Doctors] ([ID]),
    CONSTRAINT [FK_Patient_Medical_Aid] FOREIGN KEY ([Medical_Aid_ID]) REFERENCES [dbo].[Medical_Aid] ([ID]),
    CONSTRAINT [FK_Patient_Users] FOREIGN KEY ([User_ID]) REFERENCES [dbo].[Users] ([ID])
);