CREATE TABLE [dbo].[Staff] (
    [ID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[ID_Number] [nvarchar](50) NOT NULL,
	[Gender] [char](1) NOT NULL,
	[DOB] [nvarchar](50) NOT NULL,
	[Phone] [nvarchar](50) NOT NULL,
	[Street_Address] [nvarchar](50) NOT NULL,
	[Suburb] [nvarchar](50) NOT NULL,
	[City] [nvarchar](50) NOT NULL,
	[Country] [nvarchar](50) NOT NULL,
	[Employee_Type] [nvarchar](50) NOT NULL,
	[Practice_ID] [int] NOT NULL,
	[User_ID] [int] NOT NULL,
	[Email] [nvarchar](50) NULL,
	[DeletedStatus] [int] NULL DEFAULT ((0)),
    CONSTRAINT [PK_Staff] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_Staff_Practice] FOREIGN KEY ([Practice_ID]) REFERENCES [dbo].[Practice] ([ID]),
    CONSTRAINT [FK_Staff_Users] FOREIGN KEY ([User_ID]) REFERENCES [dbo].[Users] ([ID])
);
