//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessLevel
    {
        public AccessLevel()
        {
            this.Users = new HashSet<Users>();
        }
    
        public int ID { get; set; }
        public string Level { get; set; }
    
        public virtual ICollection<Users> Users { get; set; }
    }
}
