//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        public int ID { get; set; }
        public bool App_Status { get; set; }
        public System.DateTime Date_Time { get; set; }
        public string Details { get; set; }
        public int Patient_ID { get; set; }
        public int Doctor_ID { get; set; }
    
        public virtual Doctors Doctors { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
