//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultation
    {
        public int ID { get; set; }
        public int Patient_ID { get; set; }
        public int Doctor_ID { get; set; }
        public System.DateTime Date { get; set; }
        public string ReasonForConsultation { get; set; }
        public string Symptoms { get; set; }
        public string ClinicalFindings { get; set; }
        public string Diagnosis { get; set; }
        public string TestResultSummary { get; set; }
        public string TreatmentPlan { get; set; }
        public Nullable<int> Presciption_ID { get; set; }
        public Nullable<int> Referral_ID { get; set; }
    }
}
