//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEdmx
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DoConnectEntities : DbContext
    {
        public DoConnectEntities()
            : base("name=DoConnectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccessLevel> AccessLevel { get; set; }
        public DbSet<Appointments> Appointments { get; set; }
        public DbSet<Doctors> Doctors { get; set; }
        public DbSet<Invoice> Invoice { get; set; }
        public DbSet<Medical_Aid> Medical_Aid { get; set; }
        public DbSet<Patient> Patient { get; set; }
        public DbSet<Patient_Medical_Aid> Patient_Medical_Aid { get; set; }
        public DbSet<Practice> Practice { get; set; }
        public DbSet<Prescription> Prescription { get; set; }
        public DbSet<Staff> Staff { get; set; }
        public DbSet<Users> Users { get; set; }
    
        public virtual ObjectResult<Nullable<int>> CreateUser(Nullable<int> accessLevel)
        {
            var accessLevelParameter = accessLevel.HasValue ?
                new ObjectParameter("AccessLevel", accessLevel) :
                new ObjectParameter("AccessLevel", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CreateUser", accessLevelParameter);
        }
    
        public virtual ObjectResult<GetAllAppointments_Result> GetAllAppointments()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllAppointments_Result>("GetAllAppointments");
        }
    
        public virtual ObjectResult<GetAllDoctors_Result> GetAllDoctors()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllDoctors_Result>("GetAllDoctors");
        }
    
        public virtual ObjectResult<Login_Result> Login(string email, string password, Nullable<int> accessLevel)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var accessLevelParameter = accessLevel.HasValue ?
                new ObjectParameter("AccessLevel", accessLevel) :
                new ObjectParameter("AccessLevel", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Login_Result>("Login", emailParameter, passwordParameter, accessLevelParameter);
        }
    }
}
