//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Total { get; set; }
        public int Medical_Aid_ID { get; set; }
        public int Patient_ID { get; set; }
        public int Doctor_ID { get; set; }
    
        public virtual Doctors Doctors { get; set; }
        public virtual Medical_Aid Medical_Aid { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
