//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine_Inventory
    {
        public int ID { get; set; }
        public string DrugName { get; set; }
        public string Description { get; set; }
        public int QuantityPurchased { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public int QuantityInStock { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string DrugConcentration { get; set; }
        public int Practice_ID { get; set; }
    }
}
