//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.Appointments = new HashSet<Appointments>();
            this.Invoice = new HashSet<Invoice>();
            this.Patient_Medical_Aid = new HashSet<Patient_Medical_Aid>();
            this.Prescription = new HashSet<Prescription>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ID_Number { get; set; }
        public string Gender { get; set; }
        public System.DateTime DOB { get; set; }
        public string Cell_Number { get; set; }
        public string Street_Address { get; set; }
        public string Suburb { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public int Medical_Aid_ID { get; set; }
        public int Doctor_ID { get; set; }
        public int User_ID { get; set; }
        public string Allergies { get; set; }
        public string PreviousIllnesses { get; set; }
        public string PreviousMedication { get; set; }
        public string RiskFactors { get; set; }
        public string SocialHistory { get; set; }
        public string FamilyHistory { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Appointments> Appointments { get; set; }
        public virtual Doctors Doctors { get; set; }
        public virtual ICollection<Invoice> Invoice { get; set; }
        public virtual Medical_Aid Medical_Aid { get; set; }
        public virtual ICollection<Patient_Medical_Aid> Patient_Medical_Aid { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Prescription> Prescription { get; set; }
    }
}
