//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription_DrugDetails
    {
        public int ID { get; set; }
        public int Prescription_ID { get; set; }
        public string DrugName { get; set; }
        public string Strength { get; set; }
        public string IntakeRoute { get; set; }
        public string Frequency { get; set; }
        public int DispenseNumber { get; set; }
        public int RefillNumber { get; set; }
    }
}
