//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ID_Number { get; set; }
        public string Gender { get; set; }
        public System.DateTime DOB { get; set; }
        public string Phone { get; set; }
        public string Employee_Type { get; set; }
        public int Practice_ID { get; set; }
        public int User_ID { get; set; }
        public string Email { get; set; }
    
        public virtual Practice Practice { get; set; }
        public virtual Users Users { get; set; }
    }
}
